name: Githubjobs
on: [push]
jobs:
  Display-python-version:
  steps:
    - name: Display python version
    - run: python --version
  Run-pylint:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      -name: Pylint
      run: |
        find. -name '*.py' -exec pylint {}\;


name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install flask
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
